# Generated by Django 5.2.1 on 2025-10-28 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_postmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('skills_required', models.TextField()),
                ('salary', models.CharField(max_length=100, null=True)),
                ('application_deadline', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfomodel',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='user_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Job_Seeker', 'Job_Seeker')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='job_seekerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(null=True, upload_to='job/file')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_app.employeemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
