# Generated by Django 5.2.6 on 2025-10-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_employeemodel_remove_userinfomodel_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seekermodel',
            name='skill',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='job_stataus',
            field=models.CharField(choices=[('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
