# Generated by Django 5.2.6 on 2025-10-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_job_seekermodel_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seekermodel',
            name='publishdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
