# Generated by Django 5.2.6 on 2025-10-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_job_seekermodel_publishdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='job_stataus',
        ),
        migrations.AddField(
            model_name='job_seekermodel',
            name='job_stataus',
            field=models.CharField(choices=[('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
