# Generated by Django 5.2.6 on 2025-10-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_remove_employeemodel_job_stataus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seekermodel',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.employeemodel'),
        ),
    ]
