# Generated by Django 5.2.6 on 2025-10-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_job_seekermodel_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seekermodel',
            name='job',
        ),
    ]
