# Generated by Django 5.2.6 on 2025-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_remove_job_seekermodel_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seekermodel',
            name='job_stataus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
